# Security Allowlist
# Exceptions for known false positives or accepted risks

bandit:
  # Example: B104 - hardcoded bind to 0.0.0.0 in development server
  - id: B104
    file: src/orchestrator/cli.py
    reason: "Intentional binding to 0.0.0.0 for local development server"

pip_audit:
  # Add CVE exceptions here if needed
  - id: GHSA-wj6h-64fc-37mp
    package: ecdsa
    reason: "Timing attack on P-256 curve - out of scope for upstream project, no fix available"
  - id: PYSEC-2023-243
    package: localstack
    reason: "Dev dependency for local testing only, not used in production"

gitleaks:
  # Add secret exceptions here if needed
  # - fingerprint: "abc123"
  #   reason: "Test data, not a real secret"
