from __future__ import annotations
from typing import Protocol, Iterable, Optional
from orchestrator.models.execution import Execution, ExecutionCreate


class ExecutionRepository(Protocol):
    def create(self, payload: ExecutionCreate) -> Execution: ...

    def get(self, execution_id: str) -> Optional[Execution]: ...

    def list(self, limit: int = 100) -> Iterable[Execution]: ...

    def update(self, execution_id: str, **fields) -> Optional[Execution]: ...

    def delete(self, execution_id: str) -> bool: ...
